---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/vagrant"]
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18.6

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[simple::default]
    attributes:
      web:
        backends:
          - localhost
  - name: web
    run_list:
      - recipe[simple::web]
    attributes:
      web:
        backends:
          - localhost
  - name: app
    run_list:
      - recipe[simple::app]
